# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev408+gc6e4b2e'
__version_tuple__ = version_tuple = (0, 1, 'dev408', 'gc6e4b2e')
